---
title: "Pitch Pine Project R Code webpage repo"
author: "Kathleen Stutzman"
date: "2023-10-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown code for understory vegetative community (quick look)

### [Descriptive Statistics by Region-Group](Markdown/VegDS_Region.Group.html)

### [NH & ME NMDS](Markdown/Veg_NH.ME.html)

### [MA & LI NMDS](Markdown/Veg_MA.LI.html)

### [APB NMDS](Markdown/Veg_APB.html)

### [Veg NMDS overall](Markdown/vegNMDS_TDKD.html)

#### [Veg NMDS code](veg_NMDS.html)

#### [Vegetation descriptive statistics](Markdown/Veg_DS_bySite.html) 
Species richness, species diversity, species number, evenness, and beta diversity by Site & Treatment type


## R Markdown code for Pitch Pine Regeneration project

### [Small seedling models for TD & KD](Markdown/SS_Models_TDKD.html)

### [Large seedling models for TD & KD](Markdown/LS_Models_TDKD.html)

### [Sapling models for TD & KD](Markdown/SA_Models_TDKD.html)


### Below are the full scripts for generating models above

#### [Small seedling GLMM code](Markdown/SS_LR.html)

#### [Large seedling GLMM code](Markdown/LS_LR.html)

#### [Sapling GLMM code](Markdown/SA_LR.html)









